name: SilenceChat
author: RoboMWM
version: ${project.version}
main: com.robomwm.silencechat.SilenceChat
commands:
    silence:
        aliases: [unsilence, disablechat, enablechat, ignoreall, chat, chatoff, chaton, globalchat, gchat, global]
