name: DisableChat
author: RoboMWM
version: ${project.version}
main: me.robomwm.DisableChat.DisableChat
commands:
    gchat:
        aliases: [disablechat, enablechat, ignoreall, chat, chatoff, chaton, globalchat, global]
